version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: nerd-axe-influxdb
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - /data/.nerd-axe/influxdb:/var/lib/influxdb2
    networks:
      - nerd-axe-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: nerd-axe-grafana
    ports:
      - "3300:3000"
    depends_on:
      - influxdb
    volumes:
      - /data/.nerd-axe/grafana:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${DOCKER_GRAFANA_INIT_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${DOCKER_GRAFANA_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    networks:
      - nerd-axe-net
    restart: unless-stopped

networks:
  nerd-axe-net:
    name: nerd-axe-net
